# Generated by Django 5.2.1 on 2025-05-19 18:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(default=0, verbose_name='content'),
            preserve_default=False,
        ),
    ]
