# Generated by Django 5.2 on 2025-05-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0002_alter_project_options_alter_project_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
